### ISSUE TITLE
Notes from getting this running on macOS

### ISSUE THREAD

**Issue by robertknight** [xd009642/xd-tts#35]
Hello, thank-you for the talk at RustNation, it was very interesting. I got the demo running on macOS locally and made a few notes of issues I encountered in the process, in case this is helpful for anyone else.

1. cargo initially failed to clone the dependencies that are hosted in git, because I didn't have SSH-based auth already set up for github.com. As a workaround I changed the dependencies to use HTTPS:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 0d33f23..af167b6 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -16,7 +16,7 @@ csv = "1.3.0"
 derive = "1.0.0"
 deunicode = "1.3.2"
 features = "0.10.0"
-griffin-lim = { git = "ssh://git@github.com/emotechlab/griffin-lim.git" }
+griffin-lim = { git = "https://github.com/emotechlab/griffin-lim.git" }
 hound = "3.5.0"
 ndarray = "0.15.6"
 ndarray-npy = "0.8.1" # Just for convenient moving to/from python for checking
@@ -26,7 +26,7 @@ ort = { version = "2.0.0-rc.0", features = ["load-dynamic"] }
 regex = "1.6.0"
 serde =  { version = "1.0.192", features = ["derive"] }
 serde_json = "1.0.108"
-ssml-parser = { git = "ssh://git@github.com/emotechlab/ssml-parser.git", version = "0.1.4" }
+ssml-parser = { git = "https://github.com/emotechlab/ssml-parser.git", version = "0.1.4" }
 #tch = "0.8.0"
 tracing = "0.1.40"
 tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
```

2. The build initially failed with errors about cblas symbols not being found. A workaround is to use one of the methods mentioned in https://github.com/rust-ndarray/ndarray/issues/1197 to link the Accelerate system library (which contains the cblas APIs on macOS) with the binary.
3. After downloading [ONNX Runtime 1.17](https://github.com/microsoft/onnxruntime/releases/tag/v1.17.0) for macOS and setting `ORT_DYLIB_PATH` to point to the `libonnxruntime.1.17.0.dylib` file from the extracted archive, the system refused to load the library due to it not being signed. The workaround was to first open the downloaded `libonnxruntime.1.17.0.dylib` in Finder first, which shows  a prompt allowing the user to bypass the Gatekeeper checks for the file, then try running the Rust app again.
4. The `download_data.sh` script saves the `data/cmudict-0.7b` file without a file extension, but the code that loads the file expects it to have a .txt extension. I renamed the downloaded file to resolve the issue.

With the above fixes, I was able to run the demo with:

```
RUSTFLAGS='-l framework=Accelerate' cargo run --release --bin app -- -i 'this is a test for the text to speech system'
ffplay output.wav
```

**Comment by xd009642** [comment]
Cool thanks for this (and glad you enjoyed the talk), I've applied the change to the Cargo.toml, and added the stuff about cblas and ort to the readme to hopefully help others :smile:
